sudo: false
language: python
python:
  - "3.4"
  - "3.5"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - python-opencv

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest h5py pillow scikit-image pandas scikit-learn pytz
  - source activate test-environment
  - conda install -q -c https://conda.binstar.org/menpo opencv3
  - pip install git+https://github.com/Theano/Theano.git#egg=theano
  - pip install git+https://github.com/fchollet/keras.git#egg=keras
  - pip install git+git://github.com/nebw/saliency-localizer.git#egg=saliency_localizer>=0.0.1
  - CC=/usr/bin/gcc-4.9 CXX=/usr/bin/g++-4.9 pip install pycapnp
  - pip install git+git://github.com/BioroboticsLab/bb_binary.git#egg=bb_binary
  - pip install .
  - ./get_test_models.sh
script:
  - py.test
